/*
 * Stakkd API
 *
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Stakkd.Client.OpenAPIDateConverter;

namespace Stakkd.Stakkd.model
{
    /// <summary>
    /// DemographicsAppendResponseLifeStylesBook
    /// </summary>
    [DataContract(Name = "demographicsAppendResponse_lifeStyles_book")]
    public partial class DemographicsAppendResponseLifeStylesBook : IEquatable<DemographicsAppendResponseLifeStylesBook>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DemographicsAppendResponseLifeStylesBook" /> class.
        /// </summary>
        /// <param name="reader">Indicates whether the person is flagged as a book reader..</param>
        /// <param name="buyer">Indicates whether the person is flagged as a book buyer..</param>
        public DemographicsAppendResponseLifeStylesBook(bool reader = default(bool), bool buyer = default(bool))
        {
            this.Reader = reader;
            this.Buyer = buyer;
        }

        /// <summary>
        /// Indicates whether the person is flagged as a book reader.
        /// </summary>
        /// <value>Indicates whether the person is flagged as a book reader.</value>
        [DataMember(Name = "reader", EmitDefaultValue = true)]
        public bool Reader { get; set; }

        /// <summary>
        /// Indicates whether the person is flagged as a book buyer.
        /// </summary>
        /// <value>Indicates whether the person is flagged as a book buyer.</value>
        [DataMember(Name = "buyer", EmitDefaultValue = true)]
        public bool Buyer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DemographicsAppendResponseLifeStylesBook {\n");
            sb.Append("  Reader: ").Append(Reader).Append("\n");
            sb.Append("  Buyer: ").Append(Buyer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DemographicsAppendResponseLifeStylesBook);
        }

        /// <summary>
        /// Returns true if DemographicsAppendResponseLifeStylesBook instances are equal
        /// </summary>
        /// <param name="input">Instance of DemographicsAppendResponseLifeStylesBook to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DemographicsAppendResponseLifeStylesBook input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Reader == input.Reader ||
                    this.Reader.Equals(input.Reader)
                ) && 
                (
                    this.Buyer == input.Buyer ||
                    this.Buyer.Equals(input.Buyer)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Reader.GetHashCode();
                hashCode = (hashCode * 59) + this.Buyer.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
