/*
 * Stakkd API
 *
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Stakkd.Client.OpenAPIDateConverter;

namespace Stakkd.Stakkd.model
{
    /// <summary>
    /// DemographicsAppendResponseDemographicsFamily
    /// </summary>
    [DataContract(Name = "demographicsAppendResponse_demographics_family")]
    public partial class DemographicsAppendResponseDemographicsFamily : IEquatable<DemographicsAppendResponseDemographicsFamily>, IValidatableObject
    {
        /// <summary>
        /// The marital status for the person.
        /// </summary>
        /// <value>The marital status for the person.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MarriedEnum
        {
            /// <summary>
            /// Enum INFERREDMARRIED for value: INFERREDMARRIED
            /// </summary>
            [EnumMember(Value = "INFERREDMARRIED")]
            INFERREDMARRIED = 1,

            /// <summary>
            /// Enum INFERREDSINGLE for value: INFERREDSINGLE
            /// </summary>
            [EnumMember(Value = "INFERREDSINGLE")]
            INFERREDSINGLE = 2,

            /// <summary>
            /// Enum SINGLE for value: SINGLE
            /// </summary>
            [EnumMember(Value = "SINGLE")]
            SINGLE = 3,

            /// <summary>
            /// Enum MARRIED for value: MARRIED
            /// </summary>
            [EnumMember(Value = "MARRIED")]
            MARRIED = 4

        }


        /// <summary>
        /// The marital status for the person.
        /// </summary>
        /// <value>The marital status for the person.</value>
        [DataMember(Name = "married", EmitDefaultValue = false)]
        public MarriedEnum? Married { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DemographicsAppendResponseDemographicsFamily" /> class.
        /// </summary>
        /// <param name="isSingleParent">Indicates whether the person is flagged as being a single parent..</param>
        /// <param name="children">children.</param>
        /// <param name="married">The marital status for the person..</param>
        public DemographicsAppendResponseDemographicsFamily(bool isSingleParent = default(bool), DemographicsAppendResponseDemographicsFamilyChildren children = default(DemographicsAppendResponseDemographicsFamilyChildren), MarriedEnum? married = default(MarriedEnum?))
        {
            this.IsSingleParent = isSingleParent;
            this.Children = children;
            this.Married = married;
        }

        /// <summary>
        /// Indicates whether the person is flagged as being a single parent.
        /// </summary>
        /// <value>Indicates whether the person is flagged as being a single parent.</value>
        [DataMember(Name = "isSingleParent", EmitDefaultValue = true)]
        public bool IsSingleParent { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name = "children", EmitDefaultValue = false)]
        public DemographicsAppendResponseDemographicsFamilyChildren Children { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DemographicsAppendResponseDemographicsFamily {\n");
            sb.Append("  IsSingleParent: ").Append(IsSingleParent).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Married: ").Append(Married).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DemographicsAppendResponseDemographicsFamily);
        }

        /// <summary>
        /// Returns true if DemographicsAppendResponseDemographicsFamily instances are equal
        /// </summary>
        /// <param name="input">Instance of DemographicsAppendResponseDemographicsFamily to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DemographicsAppendResponseDemographicsFamily input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IsSingleParent == input.IsSingleParent ||
                    this.IsSingleParent.Equals(input.IsSingleParent)
                ) && 
                (
                    this.Children == input.Children ||
                    (this.Children != null &&
                    this.Children.Equals(input.Children))
                ) && 
                (
                    this.Married == input.Married ||
                    this.Married.Equals(input.Married)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.IsSingleParent.GetHashCode();
                if (this.Children != null)
                {
                    hashCode = (hashCode * 59) + this.Children.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Married.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
