/*
 * Stakkd API
 *
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Stakkd.Client.OpenAPIDateConverter;

namespace Stakkd.Stakkd.model
{
    /// <summary>
    /// DemographicsAppendResponseDemographics
    /// </summary>
    [DataContract(Name = "demographicsAppendResponse_demographics")]
    public partial class DemographicsAppendResponseDemographics : IEquatable<DemographicsAppendResponseDemographics>, IValidatableObject
    {
        /// <summary>
        /// The demographics level for the data.
        /// </summary>
        /// <value>The demographics level for the data.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LevelEnum
        {
            /// <summary>
            /// Enum ZIP9 for value: ZIP9
            /// </summary>
            [EnumMember(Value = "ZIP9")]
            ZIP9 = 1,

            /// <summary>
            /// Enum ZIP7 for value: ZIP7
            /// </summary>
            [EnumMember(Value = "ZIP7")]
            ZIP7 = 2,

            /// <summary>
            /// Enum ZIP5 for value: ZIP5
            /// </summary>
            [EnumMember(Value = "ZIP5")]
            ZIP5 = 3

        }


        /// <summary>
        /// The demographics level for the data.
        /// </summary>
        /// <value>The demographics level for the data.</value>
        [DataMember(Name = "level", EmitDefaultValue = false)]
        public LevelEnum? Level { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DemographicsAppendResponseDemographics" /> class.
        /// </summary>
        /// <param name="level">The demographics level for the data..</param>
        /// <param name="person">person.</param>
        /// <param name="residence">residence.</param>
        /// <param name="family">family.</param>
        /// <param name="vehicle">vehicle.</param>
        public DemographicsAppendResponseDemographics(LevelEnum? level = default(LevelEnum?), DemographicsAppendResponseDemographicsPerson person = default(DemographicsAppendResponseDemographicsPerson), DemographicsAppendResponseDemographicsResidence residence = default(DemographicsAppendResponseDemographicsResidence), DemographicsAppendResponseDemographicsFamily family = default(DemographicsAppendResponseDemographicsFamily), DemographicsAppendResponseDemographicsVehicle vehicle = default(DemographicsAppendResponseDemographicsVehicle))
        {
            this.Level = level;
            this.Person = person;
            this.Residence = residence;
            this.Family = family;
            this.Vehicle = vehicle;
        }

        /// <summary>
        /// Gets or Sets Person
        /// </summary>
        [DataMember(Name = "person", EmitDefaultValue = false)]
        public DemographicsAppendResponseDemographicsPerson Person { get; set; }

        /// <summary>
        /// Gets or Sets Residence
        /// </summary>
        [DataMember(Name = "residence", EmitDefaultValue = false)]
        public DemographicsAppendResponseDemographicsResidence Residence { get; set; }

        /// <summary>
        /// Gets or Sets Family
        /// </summary>
        [DataMember(Name = "family", EmitDefaultValue = false)]
        public DemographicsAppendResponseDemographicsFamily Family { get; set; }

        /// <summary>
        /// Gets or Sets Vehicle
        /// </summary>
        [DataMember(Name = "vehicle", EmitDefaultValue = false)]
        public DemographicsAppendResponseDemographicsVehicle Vehicle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DemographicsAppendResponseDemographics {\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  Person: ").Append(Person).Append("\n");
            sb.Append("  Residence: ").Append(Residence).Append("\n");
            sb.Append("  Family: ").Append(Family).Append("\n");
            sb.Append("  Vehicle: ").Append(Vehicle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DemographicsAppendResponseDemographics);
        }

        /// <summary>
        /// Returns true if DemographicsAppendResponseDemographics instances are equal
        /// </summary>
        /// <param name="input">Instance of DemographicsAppendResponseDemographics to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DemographicsAppendResponseDemographics input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Level == input.Level ||
                    this.Level.Equals(input.Level)
                ) && 
                (
                    this.Person == input.Person ||
                    (this.Person != null &&
                    this.Person.Equals(input.Person))
                ) && 
                (
                    this.Residence == input.Residence ||
                    (this.Residence != null &&
                    this.Residence.Equals(input.Residence))
                ) && 
                (
                    this.Family == input.Family ||
                    (this.Family != null &&
                    this.Family.Equals(input.Family))
                ) && 
                (
                    this.Vehicle == input.Vehicle ||
                    (this.Vehicle != null &&
                    this.Vehicle.Equals(input.Vehicle))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Level.GetHashCode();
                if (this.Person != null)
                {
                    hashCode = (hashCode * 59) + this.Person.GetHashCode();
                }
                if (this.Residence != null)
                {
                    hashCode = (hashCode * 59) + this.Residence.GetHashCode();
                }
                if (this.Family != null)
                {
                    hashCode = (hashCode * 59) + this.Family.GetHashCode();
                }
                if (this.Vehicle != null)
                {
                    hashCode = (hashCode * 59) + this.Vehicle.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
