/*
 * Stakkd API
 *
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Stakkd.Client.OpenAPIDateConverter;

namespace Stakkd.Stakkd.model
{
    /// <summary>
    /// DemographicsAppendResponseDemographicsPersonWorkerType
    /// </summary>
    [DataContract(Name = "demographicsAppendResponse_demographics_person_workerType")]
    public partial class DemographicsAppendResponseDemographicsPersonWorkerType : IEquatable<DemographicsAppendResponseDemographicsPersonWorkerType>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DemographicsAppendResponseDemographicsPersonWorkerType" /> class.
        /// </summary>
        /// <param name="percentWhiteCollar">The Penetration Percentage for indicating whether the person is a white collar worker, +/- 3%..</param>
        /// <param name="percentBlueCollar">The Penetration Percentage for indicating whether the person is a blue collar worker, +/- 3%..</param>
        /// <param name="percentOther">The Penetration Percentage for indicating whether the person is some other type of worker, +/- 3%..</param>
        public DemographicsAppendResponseDemographicsPersonWorkerType(int percentWhiteCollar = default(int), int percentBlueCollar = default(int), int percentOther = default(int))
        {
            this.PercentWhiteCollar = percentWhiteCollar;
            this.PercentBlueCollar = percentBlueCollar;
            this.PercentOther = percentOther;
        }

        /// <summary>
        /// The Penetration Percentage for indicating whether the person is a white collar worker, +/- 3%.
        /// </summary>
        /// <value>The Penetration Percentage for indicating whether the person is a white collar worker, +/- 3%.</value>
        [DataMember(Name = "percentWhiteCollar", EmitDefaultValue = false)]
        public int PercentWhiteCollar { get; set; }

        /// <summary>
        /// The Penetration Percentage for indicating whether the person is a blue collar worker, +/- 3%.
        /// </summary>
        /// <value>The Penetration Percentage for indicating whether the person is a blue collar worker, +/- 3%.</value>
        [DataMember(Name = "percentBlueCollar", EmitDefaultValue = false)]
        public int PercentBlueCollar { get; set; }

        /// <summary>
        /// The Penetration Percentage for indicating whether the person is some other type of worker, +/- 3%.
        /// </summary>
        /// <value>The Penetration Percentage for indicating whether the person is some other type of worker, +/- 3%.</value>
        [DataMember(Name = "percentOther", EmitDefaultValue = false)]
        public int PercentOther { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DemographicsAppendResponseDemographicsPersonWorkerType {\n");
            sb.Append("  PercentWhiteCollar: ").Append(PercentWhiteCollar).Append("\n");
            sb.Append("  PercentBlueCollar: ").Append(PercentBlueCollar).Append("\n");
            sb.Append("  PercentOther: ").Append(PercentOther).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DemographicsAppendResponseDemographicsPersonWorkerType);
        }

        /// <summary>
        /// Returns true if DemographicsAppendResponseDemographicsPersonWorkerType instances are equal
        /// </summary>
        /// <param name="input">Instance of DemographicsAppendResponseDemographicsPersonWorkerType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DemographicsAppendResponseDemographicsPersonWorkerType input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PercentWhiteCollar == input.PercentWhiteCollar ||
                    this.PercentWhiteCollar.Equals(input.PercentWhiteCollar)
                ) && 
                (
                    this.PercentBlueCollar == input.PercentBlueCollar ||
                    this.PercentBlueCollar.Equals(input.PercentBlueCollar)
                ) && 
                (
                    this.PercentOther == input.PercentOther ||
                    this.PercentOther.Equals(input.PercentOther)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PercentWhiteCollar.GetHashCode();
                hashCode = (hashCode * 59) + this.PercentBlueCollar.GetHashCode();
                hashCode = (hashCode * 59) + this.PercentOther.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
