/**
 * Stakkd API
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DemographicsAppendResponseDemographicsPersonEducation from './DemographicsAppendResponseDemographicsPersonEducation';
import DemographicsAppendResponseDemographicsPersonFinances from './DemographicsAppendResponseDemographicsPersonFinances';
import DemographicsAppendResponseDemographicsPersonLanguage from './DemographicsAppendResponseDemographicsPersonLanguage';
import DemographicsAppendResponseDemographicsPersonRace from './DemographicsAppendResponseDemographicsPersonRace';
import DemographicsAppendResponseDemographicsPersonWorkerType from './DemographicsAppendResponseDemographicsPersonWorkerType';

/**
 * The DemographicsAppendResponseDemographicsPerson model module.
 * @module stakkd.model/DemographicsAppendResponseDemographicsPerson
 * @version v1
 */
class DemographicsAppendResponseDemographicsPerson {
    /**
     * Constructs a new <code>DemographicsAppendResponseDemographicsPerson</code>.
     * @alias module:stakkd.model/DemographicsAppendResponseDemographicsPerson
     */
    constructor() { 
        
        DemographicsAppendResponseDemographicsPerson.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DemographicsAppendResponseDemographicsPerson</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:stakkd.model/DemographicsAppendResponseDemographicsPerson} obj Optional instance to populate.
     * @return {module:stakkd.model/DemographicsAppendResponseDemographicsPerson} The populated <code>DemographicsAppendResponseDemographicsPerson</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DemographicsAppendResponseDemographicsPerson();

            if (data.hasOwnProperty('education')) {
                obj['education'] = DemographicsAppendResponseDemographicsPersonEducation.constructFromObject(data['education']);
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('ethnicity')) {
                obj['ethnicity'] = ApiClient.convertToType(data['ethnicity'], 'String');
            }
            if (data.hasOwnProperty('race')) {
                obj['race'] = DemographicsAppendResponseDemographicsPersonRace.constructFromObject(data['race']);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'String');
            }
            if (data.hasOwnProperty('workerType')) {
                obj['workerType'] = DemographicsAppendResponseDemographicsPersonWorkerType.constructFromObject(data['workerType']);
            }
            if (data.hasOwnProperty('percentMailOrderRespondent')) {
                obj['percentMailOrderRespondent'] = ApiClient.convertToType(data['percentMailOrderRespondent'], 'Number');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = DemographicsAppendResponseDemographicsPersonLanguage.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('finances')) {
                obj['finances'] = DemographicsAppendResponseDemographicsPersonFinances.constructFromObject(data['finances']);
            }
            if (data.hasOwnProperty('isSenior')) {
                obj['isSenior'] = ApiClient.convertToType(data['isSenior'], 'Boolean');
            }
            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPersonEducation} education
 */
DemographicsAppendResponseDemographicsPerson.prototype['education'] = undefined;

/**
 * The gender of the person, where: M = Male; F = Female; U = Unknown.
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPerson.GenderEnum} gender
 */
DemographicsAppendResponseDemographicsPerson.prototype['gender'] = undefined;

/**
 * The ethnicity of the person.
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPerson.EthnicityEnum} ethnicity
 */
DemographicsAppendResponseDemographicsPerson.prototype['ethnicity'] = undefined;

/**
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPersonRace} race
 */
DemographicsAppendResponseDemographicsPerson.prototype['race'] = undefined;

/**
 * The date of birth as the person, formatted: yyyyMM
 * @member {String} dateOfBirth
 */
DemographicsAppendResponseDemographicsPerson.prototype['dateOfBirth'] = undefined;

/**
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPersonWorkerType} workerType
 */
DemographicsAppendResponseDemographicsPerson.prototype['workerType'] = undefined;

/**
 * The Penetration Percentage for indicating whether the person is a mail order respondent, +/- 3%.
 * @member {Number} percentMailOrderRespondent
 */
DemographicsAppendResponseDemographicsPerson.prototype['percentMailOrderRespondent'] = undefined;

/**
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPersonLanguage} language
 */
DemographicsAppendResponseDemographicsPerson.prototype['language'] = undefined;

/**
 * @member {module:stakkd.model/DemographicsAppendResponseDemographicsPersonFinances} finances
 */
DemographicsAppendResponseDemographicsPerson.prototype['finances'] = undefined;

/**
 * Indicates whether the person is flagged as a senior.
 * @member {Boolean} isSenior
 */
DemographicsAppendResponseDemographicsPerson.prototype['isSenior'] = undefined;

/**
 * The age of the person.
 * @member {Number} age
 */
DemographicsAppendResponseDemographicsPerson.prototype['age'] = undefined;





/**
 * Allowed values for the <code>gender</code> property.
 * @enum {String}
 * @readonly
 */
DemographicsAppendResponseDemographicsPerson['GenderEnum'] = {

    /**
     * value: "M"
     * @const
     */
    "M": "M",

    /**
     * value: "F"
     * @const
     */
    "F": "F",

    /**
     * value: "U"
     * @const
     */
    "U": "U"
};


/**
 * Allowed values for the <code>ethnicity</code> property.
 * @enum {String}
 * @readonly
 */
DemographicsAppendResponseDemographicsPerson['EthnicityEnum'] = {

    /**
     * value: "ASIAN"
     * @const
     */
    "ASIAN": "ASIAN",

    /**
     * value: "AFRICANAMERICAN"
     * @const
     */
    "AFRICANAMERICAN": "AFRICANAMERICAN",

    /**
     * value: "HISPANIC"
     * @const
     */
    "HISPANIC": "HISPANIC"
};



export default DemographicsAppendResponseDemographicsPerson;

