/*
 * Stakkd API
 *
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Stakkd.Stakkd;
using Stakkd.Stakkd.model;
using Stakkd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Stakkd.Test.Model
{
    /// <summary>
    ///  Class for testing DemographicsAppendResponseDemographicsPerson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DemographicsAppendResponseDemographicsPersonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DemographicsAppendResponseDemographicsPerson
        //private DemographicsAppendResponseDemographicsPerson instance;

        public DemographicsAppendResponseDemographicsPersonTests()
        {
            // TODO uncomment below to create an instance of DemographicsAppendResponseDemographicsPerson
            //instance = new DemographicsAppendResponseDemographicsPerson();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DemographicsAppendResponseDemographicsPerson
        /// </summary>
        [Fact]
        public void DemographicsAppendResponseDemographicsPersonInstanceTest()
        {
            // TODO uncomment below to test "IsType" DemographicsAppendResponseDemographicsPerson
            //Assert.IsType<DemographicsAppendResponseDemographicsPerson>(instance);
        }


        /// <summary>
        /// Test the property 'Education'
        /// </summary>
        [Fact]
        public void EducationTest()
        {
            // TODO unit test for the property 'Education'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Ethnicity'
        /// </summary>
        [Fact]
        public void EthnicityTest()
        {
            // TODO unit test for the property 'Ethnicity'
        }
        /// <summary>
        /// Test the property 'Race'
        /// </summary>
        [Fact]
        public void RaceTest()
        {
            // TODO unit test for the property 'Race'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Fact]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'WorkerType'
        /// </summary>
        [Fact]
        public void WorkerTypeTest()
        {
            // TODO unit test for the property 'WorkerType'
        }
        /// <summary>
        /// Test the property 'PercentMailOrderRespondent'
        /// </summary>
        [Fact]
        public void PercentMailOrderRespondentTest()
        {
            // TODO unit test for the property 'PercentMailOrderRespondent'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Finances'
        /// </summary>
        [Fact]
        public void FinancesTest()
        {
            // TODO unit test for the property 'Finances'
        }
        /// <summary>
        /// Test the property 'IsSenior'
        /// </summary>
        [Fact]
        public void IsSeniorTest()
        {
            // TODO unit test for the property 'IsSenior'
        }
        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }

    }

}
