/*
 * Stakkd API
 * # Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.stakkd;

import com.ApiException;
import com.stakkd.model.DemographicsAppendRequest;
import com.stakkd.model.DemographicsAppendResponse;
import com.stakkd.model.EmailAppendRequest;
import com.stakkd.model.EmailAppendResponse;
import com.stakkd.model.MobileAppendRequest;
import com.stakkd.model.MobileAppendResponse;
import com.stakkd.model.PhoneAppendRequest;
import com.stakkd.model.PhoneAppendResponse;
import com.stakkd.model.VehicleAppendRequest;
import com.stakkd.model.VehicleAppendResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppendApi
 */
@Ignore
public class AppendApiTest {

    private final AppendApi api = new AppendApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appendDemographicsPostTest() throws ApiException {
        String contentType = null;
        String xApiKey = null;
        DemographicsAppendRequest demographicsAppendRequest = null;
                DemographicsAppendResponse response = api.appendDemographicsPost(contentType, xApiKey, demographicsAppendRequest);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appendEmailPostTest() throws ApiException {
        String contentType = null;
        String xApiKey = null;
        EmailAppendRequest emailAppendRequest = null;
                EmailAppendResponse response = api.appendEmailPost(contentType, xApiKey, emailAppendRequest);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appendMobilePostTest() throws ApiException {
        String contentType = null;
        String xApiKey = null;
        MobileAppendRequest mobileAppendRequest = null;
                MobileAppendResponse response = api.appendMobilePost(contentType, xApiKey, mobileAppendRequest);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appendPhonePostTest() throws ApiException {
        String contentType = null;
        String xApiKey = null;
        PhoneAppendRequest phoneAppendRequest = null;
                PhoneAppendResponse response = api.appendPhonePost(contentType, xApiKey, phoneAppendRequest);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void appendVehiclePostTest() throws ApiException {
        String contentType = null;
        String xApiKey = null;
        VehicleAppendRequest vehicleAppendRequest = null;
                VehicleAppendResponse response = api.appendVehiclePost(contentType, xApiKey, vehicleAppendRequest);
        // TODO: test validations
    }
    
}
