//
// DemographicsAppendResponseDemographicsPersonRace.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DemographicsAppendResponseDemographicsPersonRace: Codable, JSONEncodable, Hashable {

    /** The Penetration Percentage for indicating whether the person is a hispanic, +/- 3%. */
    public var percentHispanic: Int?
    /** The Penetration Percentage for indicating whether the person is a black, +/- 3%. */
    public var percentBlack: Int?
    /** The Penetration Percentage for indicating whether the person is white, +/- 3%. */
    public var percentWhite: Int?
    /** The Penetration Percentage for indicating whether the person is a asian, +/- 3%. */
    public var percentAsian: Int?

    public init(percentHispanic: Int? = nil, percentBlack: Int? = nil, percentWhite: Int? = nil, percentAsian: Int? = nil) {
        self.percentHispanic = percentHispanic
        self.percentBlack = percentBlack
        self.percentWhite = percentWhite
        self.percentAsian = percentAsian
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentHispanic
        case percentBlack
        case percentWhite
        case percentAsian
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(percentHispanic, forKey: .percentHispanic)
        try container.encodeIfPresent(percentBlack, forKey: .percentBlack)
        try container.encodeIfPresent(percentWhite, forKey: .percentWhite)
        try container.encodeIfPresent(percentAsian, forKey: .percentAsian)
    }
}

