//
// PhoneAppendResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhoneAppendResponse: Codable, JSONEncodable, Hashable {

    public var address: IpLookupResponseAddress?
    public var phone: PhoneVerifyResponsePhone?
    /** The last name for the person. */
    public var lastName: String?
    /** The first name for the person. */
    public var firstName: String?

    public init(address: IpLookupResponseAddress? = nil, phone: PhoneVerifyResponsePhone? = nil, lastName: String? = nil, firstName: String? = nil) {
        self.address = address
        self.phone = phone
        self.lastName = lastName
        self.firstName = firstName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case phone
        case lastName
        case firstName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
    }
}

