//
// VehicleAppendResponseVehicles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VehicleAppendResponseVehicles: Codable, JSONEncodable, Hashable {

    public var year: String?
    public var model: String?
    public var make: String?

    public init(year: String? = nil, model: String? = nil, make: String? = nil) {
        self.year = year
        self.model = model
        self.make = make
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case year
        case model
        case make
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encodeIfPresent(make, forKey: .make)
    }
}

