/*
Stakkd API

# Introduction The Stakkd platform provides comprehensive data services that meet the business objectives of organizations ranging from Fortune 500 companies to startups. Our clients work in an array of industries, including insurance, financial, legal, travel, hospitality, retail, health, media, and telecommunications.  The Stakkd API is documented using the Open API 3.0.1 standard.  All endpoints are available at https://api.stakkd.io/v1. Detailed documentation for each endpoint is below, including the full URL for the endpoint.  # Account Types The API supports two different account types, each with different permissions.  ## Paid Account Paid accounts provide unlimited access to all of the URIs.  ## Trial Account Trial Accounts have a limited number of queries to the APIs. Keep in mind that queries which do not return results still count against the Trial Account query limits. Trial Accounts are temporary, but can be upgraded or extended by contacting [support@stakkd.io](mailto:support@stakkd.io) 

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Stakkd

import (
	"encoding/json"
)

// DemographicsAppendResponsePhones struct for DemographicsAppendResponsePhones
type DemographicsAppendResponsePhones struct {
	// The phone number.
	Phone *int32 `json:"phone,omitempty"`
}

// NewDemographicsAppendResponsePhones instantiates a new DemographicsAppendResponsePhones object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDemographicsAppendResponsePhones() *DemographicsAppendResponsePhones {
	this := DemographicsAppendResponsePhones{}
	return &this
}

// NewDemographicsAppendResponsePhonesWithDefaults instantiates a new DemographicsAppendResponsePhones object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDemographicsAppendResponsePhonesWithDefaults() *DemographicsAppendResponsePhones {
	this := DemographicsAppendResponsePhones{}
	return &this
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *DemographicsAppendResponsePhones) GetPhone() int32 {
	if o == nil || o.Phone == nil {
		var ret int32
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DemographicsAppendResponsePhones) GetPhoneOk() (*int32, bool) {
	if o == nil || o.Phone == nil {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *DemographicsAppendResponsePhones) HasPhone() bool {
	if o != nil && o.Phone != nil {
		return true
	}

	return false
}

// SetPhone gets a reference to the given int32 and assigns it to the Phone field.
func (o *DemographicsAppendResponsePhones) SetPhone(v int32) {
	o.Phone = &v
}

func (o DemographicsAppendResponsePhones) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Phone != nil {
		toSerialize["phone"] = o.Phone
	}
	return json.Marshal(toSerialize)
}

type NullableDemographicsAppendResponsePhones struct {
	value *DemographicsAppendResponsePhones
	isSet bool
}

func (v NullableDemographicsAppendResponsePhones) Get() *DemographicsAppendResponsePhones {
	return v.value
}

func (v *NullableDemographicsAppendResponsePhones) Set(val *DemographicsAppendResponsePhones) {
	v.value = val
	v.isSet = true
}

func (v NullableDemographicsAppendResponsePhones) IsSet() bool {
	return v.isSet
}

func (v *NullableDemographicsAppendResponsePhones) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDemographicsAppendResponsePhones(val *DemographicsAppendResponsePhones) *NullableDemographicsAppendResponsePhones {
	return &NullableDemographicsAppendResponsePhones{value: val, isSet: true}
}

func (v NullableDemographicsAppendResponsePhones) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDemographicsAppendResponsePhones) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


